#SkLearn DataSets

NAME
    sklearn.datasets

DESCRIPTION
    The :mod:`sklearn.datasets` module includes utilities to load datasets,
    including methods to load and fetch popular reference datasets. It also
    features some artificial data generators.

PACKAGE CONTENTS
    _base
    _california_housing
    _covtype
    _kddcup99
    _lfw
    _olivetti_faces
    _openml
    _rcv1
    _samples_generator
    _species_distributions
    _svmlight_format_fast
    _svmlight_format_io
    _twenty_newsgroups
    data (package)
    descr (package)
    images (package)
    setup
    tests (package)

In [22]:
from sklearn.datasets import *

# fetch_20newsgroups(*, data_home=None, subset='train', categories=None, shuffle=True, random_state=42, remove=(), download_if_missing=True, return_X_y=False)
        Load the filenames and data from the 20 newsgroups dataset (classification).
        
        Download it if necessary.
        
        =================   ==========
        Classes                     20
        Samples total            18846
        Dimensionality               1
        Features                  text
        =================   ==========
        
        Read more in the :ref:`User Guide <20newsgroups_dataset>`.
        
        Parameters
        ----------
        data_home : str, default=None
            Specify a download and cache folder for the datasets. If None,
            all scikit-learn data is stored in '~/scikit_learn_data' subfolders.
        
        subset : {'train', 'test', 'all'}, default='train'
            Select the dataset to load: 'train' for the training set, 'test'
            for the test set, 'all' for both, with shuffled ordering.
        
        categories : array-like, dtype=str, default=None
            If None (default), load all the categories.
            If not None, list of category names to load (other categories
            ignored).
        
        shuffle : bool, default=True
            Whether or not to shuffle the data: might be important for models that
            make the assumption that the samples are independent and identically
            distributed (i.i.d.), such as stochastic gradient descent.
        
        random_state : int, RandomState instance or None, default=None
            Determines random number generation for dataset shuffling. Pass an int
            for reproducible output across multiple function calls.
            See :term:`Glossary <random_state>`.
        
        remove : tuple, default=()
            May contain any subset of ('headers', 'footers', 'quotes'). Each of
            these are kinds of text that will be detected and removed from the
            newsgroup posts, preventing classifiers from overfitting on
            metadata.
        
            'headers' removes newsgroup headers, 'footers' removes blocks at the
            ends of posts that look like signatures, and 'quotes' removes lines
            that appear to be quoting another post.
        
            'headers' follows an exact standard; the other filters are not always
            correct.
        
        download_if_missing : bool, default=True
            If False, raise an IOError if the data is not locally available
            instead of trying to download the data from the source site.
        
        return_X_y : bool, default=False
            If True, returns `(data.data, data.target)` instead of a Bunch
            object.
        
            .. versionadded:: 0.22
        
        Returns
        -------
        bunch : :class:`~sklearn.utils.Bunch`
            Dictionary-like object, with the following attributes.
        
            data : list of shape (n_samples,)
                The data list to learn.
            target: ndarray of shape (n_samples,)
                The target labels.
            filenames: list of shape (n_samples,)
                The path to the location of the data.
            DESCR: str
                The full description of the dataset.
            target_names: list of shape (n_classes,)
                The names of target classes.
        
        (data, target) : tuple if `return_X_y=True`
            .. versionadded:: 0.22


In [ ]:
fetch_20newsgroups() #Live News Data

In [ ]:
# datasets.fetch_20newsgroups_vectorized()

# fetch_california_housing

In [13]:
fetch_california_housing(as_frame=True).frame

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  MedHouseVal  
0        -122.23        4.526  
1        -122.22        3.585  
2        -122.24        3.521  
3        -122.25        3.413  
4        -122.25        3.422  
...          ...          ...  
20635    -121.09        0.781  
20636    -121.21        0.771  
20637    -121.22        0.923  
20638    -121.32        0.847  
20639    -121.24        0.894  

[20640 rows x 9 columns]

# fetch_covtype

In [10]:
fetch_covtype()

{'data': array([[2.596e+03, 5.100e+01, 3.000e+00, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [2.590e+03, 5.600e+01, 2.000e+00, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [2.804e+03, 1.390e+02, 9.000e+00, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        ...,
        [2.386e+03, 1.590e+02, 1.700e+01, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [2.384e+03, 1.700e+02, 1.500e+01, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [2.383e+03, 1.650e+02, 1.300e+01, ..., 0.000e+00, 0.000e+00,
         0.000e+00]]),
 'target': array([5, 5, 2, ..., 3, 3, 3], dtype=int32),
 'frame': None,
 'target_names': ['Cover_Type'],
 'feature_names': ['Elevation',
  'Aspect',
  'Slope',
  'Horizontal_Distance_To_Hydrology',
  'Vertical_Distance_To_Hydrology',
  'Horizontal_Distance_To_Roadways',
  'Hillshade_9am',
  'Hillshade_Noon',
  'Hillshade_3pm',
  'Horizontal_Distance_To_Fire_Points',
  'Wilderness_Area_0',
  'Wilderness_Area_1',
  'Wilderness_Area_2',

# fetch_kddcup99
KDD Cup 1999 Data
Abstract
This is the data set used for The Third International Knowledge Discovery and Data Mining Tools Competition, which was held in conjunction with KDD-99 The Fifth International Conference on Knowledge Discovery and Data Mining. The competition task was to build a network intrusion detector, a predictive model capable of distinguishing between ``bad'' connections, called intrusions or attacks, and ``good'' normal connections. This database contains a standard set of data to be audited, which includes a wide variety of intrusions simulated in a military network environment.

Information files:

task description. This is the original task decription given to competition participants.
Data files:

kddcup.names A list of features.
kddcup.data.gz The full data set (18M; 743M Uncompressed)
kddcup.data_10_percent.gz A 10% subset. (2.1M; 75M Uncompressed)
kddcup.newtestdata_10_percent_unlabeled.gz (1.4M; 45M Uncompressed)
kddcup.testdata.unlabeled.gz (11.2M; 430M Uncompressed)
kddcup.testdata.unlabeled_10_percent.gz (1.4M;45M Uncompressed)
corrected.gz Test data with corrected labels.
training_attack_types A list of intrusion types.
typo-correction.txt A brief note on a typo in the data set that has been corrected (6/26/07)


In [16]:
fetch_kddcup99(as_frame=True).frame

duration protocol_type  service   flag src_bytes dst_bytes land  \
0             0        b'tcp'  b'http'  b'SF'       181      5450    0   
1             0        b'tcp'  b'http'  b'SF'       239       486    0   
2             0        b'tcp'  b'http'  b'SF'       235      1337    0   
3             0        b'tcp'  b'http'  b'SF'       219      1337    0   
4             0        b'tcp'  b'http'  b'SF'       217      2032    0   
...         ...           ...      ...    ...       ...       ...  ...   
494016        0        b'tcp'  b'http'  b'SF'       310      1881    0   
494017        0        b'tcp'  b'http'  b'SF'       282      2286    0   
494018        0        b'tcp'  b'http'  b'SF'       203      1200    0   
494019        0        b'tcp'  b'http'  b'SF'       291      1200    0   
494020        0        b'tcp'  b'http'  b'SF'       219      1234    0   

       wrong_fragment urgent hot  ... dst_host_srv_count  \
0                   0      0   0  ...                  9   
1                   0      0   0  ...                 19   
2                   0      0   0  ...                 29   
3                   0      0   0  ...                 39   
4                   0      0   0  ...                 49   
...               ...    ...  ..  ...                ...   
494016              0      0   0  ...                255   
494017              0      0   0  ...                255   
494018              0      0   0  ...                255   
494019              0      0   0  ...                255   
494020              0      0   0  ...                255   

       dst_host_same_srv_rate dst_host_diff_srv_rate  \
0                         1.0                    0.0   
1                         1.0                    0.0   
2                         1.0                    0.0   
3                         1.0                    0.0   
4                         1.0                    0.0   
...                       ...                    ...   
494016                    1.0                    0.0   
494017                    1.0                    0.0   
494018                    1.0                    0.0   
494019                    1.0                    0.0   
494020                    1.0                    0.0   

       dst_host_same_src_port_rate dst_host_srv_diff_host_rate  \
0                             0.11                         0.0   
1                             0.05                         0.0   
2                             0.03                         0.0   
3                             0.03                         0.0   
4                             0.02                         0.0   
...                            ...                         ...   
494016                        0.01                        0.05   
494017                        0.17                        0.05   
494018                        0.06                        0.05   
494019                        0.04                        0.05   
494020                        0.17                        0.05   

       dst_host_serror_rate dst_host_srv_serror_rate dst_host_rerror_rate  \
0                       0.0                      0.0                  0.0   
1                       0.0                      0.0                  0.0   
2                       0.0                      0.0                  0.0   
3                       0.0                      0.0                  0.0   
4                       0.0                      0.0                  0.0   
...                     ...                      ...                  ...   
494016                  0.0                     0.01                  0.0   
494017                  0.0                     0.01                  0.0   
494018                 0.06                     0.01                  0.0   
494019                 0.04                     0.01                  0.0   
494020                  0.0                     0.01                  0.0   

      

# fetch_lfw_pairs

In [17]:
fetch_lfw_pairs()

{'data': array([[ 73.666664,  70.666664,  81.666664, ..., 225.66667 , 229.66667 ,
         233.33333 ],
        [ 86.333336, 113.333336, 133.33333 , ..., 106.      , 114.333336,
         122.333336],
        [ 37.333332,  35.333332,  34.      , ...,  51.333332,  52.333332,
          52.      ],
        ...,
        [ 73.      ,  94.333336, 121.333336, ...,  64.      ,  71.      ,
          82.333336],
        [119.      , 110.333336, 112.666664, ..., 145.33333 , 130.      ,
         102.333336],
        [ 23.333334,  20.      ,  23.333334, ..., 146.33333 , 151.      ,
         159.      ]], dtype=float32),
 'pairs': array([[[[ 73.666664,  70.666664,  81.666664, ..., 119.      ,
           118.      , 118.333336],
          [ 70.      ,  70.666664,  85.666664, ..., 117.      ,
           111.666664, 106.666664],
          [ 71.333336,  77.      ,  97.333336, ..., 116.      ,
           114.      , 108.333336],
          ...,
          [154.33333 , 148.      , 162.33333 , ..., 155.33333 

# fetch_lfw_people

In [18]:
fetch_lfw_people()

{'data': array([[ 34.      ,  29.333334,  22.333334, ...,  14.666667,  16.      ,
          14.      ],
        [158.      , 160.66667 , 169.66667 , ..., 138.66667 , 135.33333 ,
         130.33333 ],
        [ 77.      ,  81.333336,  88.      , ..., 192.      , 145.33333 ,
          66.333336],
        ...,
        [ 38.      ,  41.666668,  55.333332, ...,  66.      ,  63.666668,
          54.333332],
        [ 16.666666,  24.333334,  60.333332, ..., 219.      , 143.33333 ,
          69.333336],
        [ 58.333332,  48.      ,  20.      , ..., 116.      , 106.333336,
         143.33333 ]], dtype=float32),
 'images': array([[[ 34.      ,  29.333334,  22.333334, ...,  20.      ,
           25.666666,  30.666666],
         [ 37.333332,  32.      ,  25.333334, ...,  21.      ,
           26.666666,  32.      ],
         [ 33.333332,  32.333332,  40.333332, ...,  23.666666,
           28.      ,  35.666668],
         ...,
         [166.      ,  97.      ,  44.333332, ...,   9.666667,
     

In [19]:
fetch_olivetti_faces()

downloading Olivetti faces from https://ndownloader.figshare.com/files/5976027 to /root/scikit_learn_data


{'data': array([[0.30991736, 0.3677686 , 0.41735536, ..., 0.15289256, 0.16115703,
         0.1570248 ],
        [0.45454547, 0.47107437, 0.5123967 , ..., 0.15289256, 0.15289256,
         0.15289256],
        [0.3181818 , 0.40082645, 0.49173555, ..., 0.14049587, 0.14876033,
         0.15289256],
        ...,
        [0.5       , 0.53305787, 0.607438  , ..., 0.17768595, 0.14876033,
         0.19008264],
        [0.21487603, 0.21900827, 0.21900827, ..., 0.57438016, 0.59090906,
         0.60330576],
        [0.5165289 , 0.46280992, 0.28099173, ..., 0.35950413, 0.3553719 ,
         0.38429752]], dtype=float32),
 'images': array([[[0.30991736, 0.3677686 , 0.41735536, ..., 0.37190083,
          0.3305785 , 0.30578512],
         [0.3429752 , 0.40495867, 0.43801653, ..., 0.37190083,
          0.338843  , 0.3140496 ],
         [0.3429752 , 0.41735536, 0.45041323, ..., 0.38016528,
          0.338843  , 0.29752067],
         ...,
         [0.21487603, 0.20661157, 0.2231405 , ..., 0.15289256,
     

In [24]:
fetch_openml

<function sklearn.datasets._openml.fetch_openml(name: Union[str, NoneType] = None, *, version: Union[str, int] = 'active', data_id: Union[int, NoneType] = None, data_home: Union[str, NoneType] = None, target_column: Union[str, List, NoneType] = 'default-target', cache: bool = True, return_X_y: bool = False, as_frame: Union[str, bool] = 'auto')>

In [26]:

fetch_rcv1()

{'data': <804414x47236 sparse matrix of type '<class 'numpy.float64'>'
 	with 60915113 stored elements in Compressed Sparse Row format>,
 'target': <804414x103 sparse matrix of type '<class 'numpy.uint8'>'
 	with 2606875 stored elements in Compressed Sparse Row format>,
 'sample_id': array([  2286,   2287,   2288, ..., 810594, 810595, 810596], dtype=uint32),
 'target_names': array(['C11', 'C12', 'C13', 'C14', 'C15', 'C151', 'C1511', 'C152', 'C16',
        'C17', 'C171', 'C172', 'C173', 'C174', 'C18', 'C181', 'C182',
        'C183', 'C21', 'C22', 'C23', 'C24', 'C31', 'C311', 'C312', 'C313',
        'C32', 'C33', 'C331', 'C34', 'C41', 'C411', 'C42', 'CCAT', 'E11',
        'E12', 'E121', 'E13', 'E131', 'E132', 'E14', 'E141', 'E142',
        'E143', 'E21', 'E211', 'E212', 'E31', 'E311', 'E312', 'E313',
        'E41', 'E411', 'E51', 'E511', 'E512', 'E513', 'E61', 'E71', 'ECAT',
        'G15', 'G151', 'G152', 'G153', 'G154', 'G155', 'G156', 'G157',
        'G158', 'G159', 'GCAT', 'GCRIM', 'G

In [27]:

fetch_species_distributions()

{'coverages': array([[[ -128,  -128,  -128, ...,  -128,  -128,  -128],
         [ -128,  -128,  -128, ...,  -128,  -128,  -128],
         [ -128,  -128,  -128, ...,  -128,  -128,  -128],
         ...,
         [ -128,  -128,  -128, ...,  -128,  -128,  -128],
         [ -128,  -128,  -128, ...,  -128,  -128,  -128],
         [ -128,  -128,  -128, ...,  -128,  -128,  -128]],
 
        [[-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999],
         ...,
         [-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999]],
 
        [[ -128,  -128,  -128, ...,  -128,  -128,  -128],
         [ -128,  -128,  -128, ...,  -128,  -128,  -128],
         [ -128,  -128,  -128, ...,  -128,  -128,  -128],
         ...,
         [ -128,  -128,  -128, ...,  -128,  -128,  -128],
         [ 

In [35]:
get_data_home()

'/root/scikit_learn_data'

In [29]:
load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [30]:
load_breast_cancer()

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [31]:
load_diabetes()

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [32]:
load_diabetes()

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [33]:
load_digits()

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [34]:
load_files()

TypeError: ignored

In [36]:
load_iris()

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [37]:
load_linnerud()

{'data': array([[  5., 162.,  60.],
        [  2., 110.,  60.],
        [ 12., 101., 101.],
        [ 12., 105.,  37.],
        [ 13., 155.,  58.],
        [  4., 101.,  42.],
        [  8., 101.,  38.],
        [  6., 125.,  40.],
        [ 15., 200.,  40.],
        [ 17., 251., 250.],
        [ 17., 120.,  38.],
        [ 13., 210., 115.],
        [ 14., 215., 105.],
        [  1.,  50.,  50.],
        [  6.,  70.,  31.],
        [ 12., 210., 120.],
        [  4.,  60.,  25.],
        [ 11., 230.,  80.],
        [ 15., 225.,  73.],
        [  2., 110.,  43.]]),
 'feature_names': ['Chins', 'Situps', 'Jumps'],
 'target': array([[191.,  36.,  50.],
        [189.,  37.,  52.],
        [193.,  38.,  58.],
        [162.,  35.,  62.],
        [189.,  35.,  46.],
        [182.,  36.,  56.],
        [211.,  38.,  56.],
        [167.,  34.,  60.],
        [176.,  31.,  74.],
        [154.,  33.,  56.],
        [169.,  34.,  50.],
        [166.,  33.,  52.],
        [154.,  34.,  64.],
        

In [38]:
load_sample_image()

TypeError: ignored

In [39]:
load_sample_images()

{'images': [array([[[174, 201, 231],
          [174, 201, 231],
          [174, 201, 231],
          ...,
          [250, 251, 255],
          [250, 251, 255],
          [250, 251, 255]],
  
         [[172, 199, 229],
          [173, 200, 230],
          [173, 200, 230],
          ...,
          [251, 252, 255],
          [251, 252, 255],
          [251, 252, 255]],
  
         [[174, 201, 231],
          [174, 201, 231],
          [174, 201, 231],
          ...,
          [252, 253, 255],
          [252, 253, 255],
          [252, 253, 255]],
  
         ...,
  
         [[ 88,  80,   7],
          [147, 138,  69],
          [122, 116,  38],
          ...,
          [ 39,  42,  33],
          [  8,  14,   2],
          [  6,  12,   0]],
  
         [[122, 112,  41],
          [129, 120,  53],
          [118, 112,  36],
          ...,
          [  9,  12,   3],
          [  9,  15,   3],
          [ 16,  24,   9]],
  
         [[116, 103,  35],
          [104,  93,  31],
          [108

In [40]:
load_svmlight_file()

TypeError: ignored

In [41]:
load_svmlight_files()

TypeError: ignored

In [42]:
load_wine()

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [7]:
dir(datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'descr',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_boston',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circles',
 '

In [65]:
make_swiss_roll()

(array([[ 4.00355192e+00,  1.04049770e+01,  1.32522394e+01],
        [ 6.10883651e+00,  1.83778833e+01, -9.80549848e+00],
        [-6.25355639e+00,  1.88635972e+01, -8.24282214e+00],
        [-4.82932115e+00,  7.54842544e+00,  6.94787052e+00],
        [ 6.26002004e+00,  8.40045989e+00,  2.12261524e+00],
        [ 4.34972170e+00,  8.05398444e+00,  1.31143773e+01],
        [-4.25983535e+00,  1.49300322e+01,  7.22436570e+00],
        [ 5.72306759e+00,  6.35787129e+00,  3.79901019e+00],
        [ 8.45470159e+00,  1.94741727e+01, -8.22406928e+00],
        [ 3.21153990e+00,  8.74318478e+00,  6.67279407e+00],
        [ 8.29895679e+00,  1.49128523e+00,  1.06143678e+01],
        [ 1.08560788e+01,  1.66650085e+01, -5.36108277e+00],
        [ 6.34341603e+00,  9.64680376e+00,  5.16230939e-01],
        [ 5.74715980e+00,  1.81138710e+01,  1.24411134e+01],
        [ 5.13156276e-03,  1.65515370e+01, -4.71347489e+00],
        [-3.72999344e+00,  3.21277674e+00,  7.43583902e+00],
        [ 1.24145796e+01

In [ ]:
make_spd_matrix()

In [63]:
make_sparse_uncorrelated()

(array([[-4.95188670e-01, -1.71638847e+00,  3.15970618e-01,
          5.33976907e-01, -1.26169568e+00,  3.55165800e-01,
          9.37254478e-01, -4.35107287e-01,  6.08878357e-01,
         -4.47907167e-01],
        [-6.62104790e-01, -6.97908976e-01, -2.76446743e-01,
         -4.44461788e-01,  5.52626472e-01, -1.34838429e-01,
         -5.04254954e-01,  3.67246584e-01,  2.17593802e+00,
          7.45410129e-01],
        [ 1.52655397e-01,  1.74692670e-01,  1.82624739e+00,
         -6.31685489e-01,  7.89519858e-01, -2.18920526e-01,
          2.33800565e+00, -2.44763653e-01, -4.65012159e-02,
          6.68898148e-03],
        [ 6.05646683e-01, -5.58744182e-01,  4.85124150e-01,
          7.53483845e-01,  4.98111540e-01, -2.54310420e-01,
         -2.13790369e-02,  2.02140060e+00, -1.28526432e+00,
          5.12560215e-02],
        [-1.49841056e+00, -9.87627637e-01,  6.47338907e-01,
         -2.94293625e-01, -1.06055874e+00,  6.20855587e-01,
         -3.05410730e+00, -1.32304867e-01,  7.669409

In [62]:
make_sparse_spd_matrix()

array([[1.]])

In [61]:
make_sparse_coded_signal()

TypeError: ignored

In [60]:
make_s_curve()

(array([[ 8.71007727e-01,  1.04523641e+00,  1.49126931e+00],
        [ 1.02716153e-01,  4.85714326e-01, -1.99471071e+00],
        [ 3.10678280e-01,  3.29630583e-01, -4.94848732e-02],
        [-8.71532861e-01,  1.21289650e+00, -1.49033710e+00],
        [ 6.38337538e-01,  1.25179947e+00, -1.76975658e+00],
        [-8.23863677e-01,  7.25424736e-02,  4.33211995e-01],
        [ 8.16584051e-01,  1.64952621e+00, -1.57722655e+00],
        [ 2.67423720e-01,  1.40999175e+00, -3.64209664e-02],
        [ 6.61289477e-01,  1.34275804e+00, -2.49869193e-01],
        [-9.99964615e-01,  1.87476344e-01, -1.00841243e+00],
        [ 8.79223646e-01,  8.05179056e-01,  1.47640926e+00],
        [-7.03695980e-01,  1.60436557e-01,  1.71050121e+00],
        [ 3.91583865e-01,  6.96037204e-02, -7.98575779e-02],
        [-9.78913609e-01,  3.67948485e-01, -1.20427468e+00],
        [-6.65604522e-01,  1.38028945e+00, -1.74630464e+00],
        [ 8.10871575e-01,  5.62507331e-01,  1.58522414e+00],
        [ 9.03882815e-01

In [59]:
make_regression()

(array([[-2.30143961, -0.75622253, -0.38676719, ..., -0.22806804,
          0.30520964,  0.09897281],
        [ 1.92301163,  0.12105827,  0.52732663, ..., -0.06538441,
          1.03389341,  0.68476237],
        [-0.36095004,  0.29093761,  0.87876706, ...,  1.7007939 ,
          0.06255507,  0.61780133],
        ...,
        [-0.11351288,  2.61362046,  0.84767783, ...,  0.89402132,
          1.28417766,  0.49119495],
        [ 0.34393754, -1.96383981,  0.30813513, ..., -2.35251156,
          0.03630073, -0.24315635],
        [ 0.22245934,  1.10660652,  1.4115904 , ..., -0.81561563,
         -0.49493843,  0.36678647]]),
 array([-4.41624167e+02, -6.48643646e+01,  2.00188058e+02, -1.83800642e+02,
         4.53686087e+02, -2.41807820e+01,  1.64154674e+02,  1.05681524e+02,
         2.34750350e+02, -3.05504348e+02,  1.66190047e+00,  2.40497225e+02,
         1.37612319e+02,  2.75405119e+01, -1.27797180e+02, -2.60411631e+01,
        -1.88296944e+02,  1.37170117e+01, -6.93312948e+00,  6.1304570

In [57]:
make_moons()

(array([[-1.59599895e-01,  9.87181783e-01],
        [ 4.81607432e-01, -3.55142763e-01],
        [ 4.27883340e-01, -3.20172255e-01],
        [ 1.22252093e+00, -4.74927912e-01],
        [ 9.49055747e-01,  3.15108218e-01],
        [ 3.27051370e-02,  2.46345416e-01],
        [ 1.87131870e+00,  9.28244800e-03],
        [ 8.71318704e-01,  4.90717552e-01],
        [ 1.76144596e+00, -1.48228395e-01],
        [-8.38088105e-01,  5.45534901e-01],
        [ 1.09602303e+00, -4.95379113e-01],
        [ 9.26916757e-01,  3.75267005e-01],
        [ 3.45365054e-01,  9.38468422e-01],
        [-9.97945393e-01,  6.40702200e-02],
        [ 5.09442530e-02,  1.84891782e-01],
        [ 1.99179001e+00,  3.72122838e-01],
        [-6.72300890e-01,  7.40277997e-01],
        [ 9.03976974e-01, -4.95379113e-01],
        [ 7.77479066e-01, -4.74927912e-01],
        [ 1.84408430e-02,  3.08841371e-01],
        [ 9.67294863e-01,  2.53654584e-01],
        [-9.91790014e-01,  1.27877162e-01],
        [ 9.91790014e-01,  1.278

In [58]:
make_multilabel_classification()

(array([[1., 1., 4., ..., 1., 2., 3.],
        [2., 4., 0., ..., 1., 0., 1.],
        [2., 2., 3., ..., 4., 0., 0.],
        ...,
        [8., 0., 2., ..., 3., 1., 1.],
        [3., 3., 1., ..., 0., 1., 5.],
        [2., 5., 0., ..., 6., 0., 1.]]), array([[0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [1, 0, 1, 1, 0],
        [0, 1, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 1, 1],
        [1, 1, 1, 1, 0],
        [0, 0, 0, 1, 0],
        [1, 1, 1, 1, 0],
        [1, 1, 1, 1, 0],
        [1, 1, 0, 0, 0],
        [1, 1, 0, 1, 1],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 0, 1],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [1, 1, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [1, 1, 0, 1, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 0, 1, 1],
        [0, 0, 1, 1, 0],
        [0, 0, 1, 0, 1],
        [1, 1, 1, 1, 0],
        [1, 0, 1, 1, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
  

In [56]:
make_low_rank_matrix()

array([[-0.00604299,  0.01755631,  0.01700347, ..., -0.10622013,
         0.05294203, -0.06480883],
       [-0.00200893,  0.06370486,  0.0202165 , ..., -0.0343403 ,
        -0.02873495,  0.02130078],
       [ 0.06252527,  0.0002458 , -0.04768892, ...,  0.02613354,
        -0.08672604,  0.04415587],
       ...,
       [ 0.06258214,  0.01628541, -0.03705013, ..., -0.10853032,
         0.04929818, -0.11342105],
       [-0.0586894 , -0.00460933,  0.06053001, ..., -0.01969972,
        -0.01180502,  0.02402463],
       [ 0.04796454, -0.00800276, -0.05546965, ...,  0.01595293,
         0.00617173,  0.0344543 ]])

In [54]:
make_hastie_10_2()

(array([[ 0.51330951,  0.87427309, -1.53164635, ..., -0.57375373,
          0.87082745, -0.07158559],
        [ 0.08989122, -2.04508546,  1.22401409, ..., -0.00535525,
          1.81909983,  0.87042616],
        [ 0.35239423, -0.4339363 , -1.05751601, ..., -1.65388129,
         -0.86375094,  0.69097155],
        ...,
        [-0.1591155 , -0.22110936,  0.33451629, ...,  1.01344261,
         -0.8409588 ,  0.98903796],
        [-1.93149652,  0.21963684, -0.21277879, ...,  0.37480137,
          0.52278254,  0.18031224],
        [ 1.31525368, -1.83199854,  0.78816237, ..., -2.09019756,
          0.50252042,  0.95117523]]),
 array([-1.,  1., -1., ..., -1., -1.,  1.]))

In [55]:
make_hastie_10_2()

(array([[-0.34937099, -0.35732025, -1.05705542, ..., -0.48924056,
         -0.54456488, -0.04290216],
        [ 0.16626629,  1.31173548, -0.63771965, ..., -0.30889828,
         -1.08837308,  1.07538892],
        [ 0.41786845, -0.51860049,  0.48022692, ...,  1.95848234,
          1.69212544,  0.19501041],
        ...,
        [-1.01765366, -0.45013698, -2.12596309, ..., -0.64206159,
          2.64069488,  2.59370022],
        [-0.03230279,  0.26922294, -0.0646473 , ..., -0.87266966,
          1.40366491, -0.27537609],
        [ 0.33846734, -0.5716945 , -1.34592539, ..., -1.69867904,
         -1.54720955, -0.02123706]]),
 array([-1., -1.,  1., ...,  1., -1.,  1.]))

In [53]:
make_gaussian_quantiles()

(array([[ 0.31499253, -0.37647496],
        [ 0.47002425, -1.46584123],
        [ 0.56335825,  1.44756284],
        [ 1.35597676,  0.70512654],
        [-0.04323649,  0.13577565],
        [-0.12075949,  0.36500414],
        [-0.07427139, -0.80495127],
        [ 0.1536715 ,  0.30498813],
        [-0.83509532, -1.27032199],
        [-0.05923507, -0.43198036],
        [-0.38611164,  1.19189479],
        [ 1.00617631, -0.10004661],
        [ 0.45119231,  0.49622557],
        [-0.88234186,  0.50014853],
        [ 0.32829453,  0.6465219 ],
        [-0.41046486, -0.57344364],
        [ 0.94100452,  0.24356873],
        [ 0.12936993, -0.11862453],
        [-0.02552042, -1.36329645],
        [ 1.03084226,  2.56093293],
        [-0.94105317,  0.0049705 ],
        [-0.03548978, -2.43291239],
        [ 2.60531087,  1.88316062],
        [ 0.74035543,  0.25653817],
        [-0.85477826,  0.59428516],
        [-0.34188605, -1.364826  ],
        [ 1.00469015, -0.75426841],
        [-0.06422007,  0.016

In [52]:
make_friedman3()

(array([[8.27230801e+01, 1.73292966e+03, 1.80872285e-01, 1.01922764e+01],
        [1.46398965e+01, 1.51808297e+03, 7.03694199e-01, 7.71432395e+00],
        [5.29123023e+01, 6.55530697e+02, 1.95101234e-01, 2.83368510e+00],
        [4.05324803e+01, 5.49878071e+02, 1.91905221e-01, 8.38739599e+00],
        [4.95303704e+01, 1.73929727e+03, 2.45222845e-01, 7.39595679e+00],
        [4.72895190e+01, 1.77468270e+02, 7.53381224e-01, 2.96215084e+00],
        [3.18976234e+01, 1.02367516e+03, 1.49384257e-01, 2.48735572e+00],
        [8.16041931e+01, 1.69006506e+03, 5.34006973e-03, 1.58790079e+00],
        [4.30192217e+01, 2.84425137e+02, 7.00819728e-01, 2.79995721e+00],
        [7.19885456e+01, 5.36561195e+02, 6.28570461e-01, 6.39773849e+00],
        [8.43201590e+01, 4.00009094e+02, 3.54343990e-01, 6.56202154e+00],
        [2.51841496e+01, 1.72822292e+03, 2.59019516e-01, 2.02355578e+00],
        [6.73174693e+01, 1.17155905e+03, 9.69875519e-01, 6.27857551e+00],
        [4.63271641e+01, 3.92688993e+0

In [51]:
make_friedman2()

(array([[1.93789885e+01, 5.07601547e+02, 3.59267290e-01, 4.77863467e+00],
        [1.99758742e+01, 1.28237089e+03, 3.71505574e-01, 5.10011245e+00],
        [8.48759092e+01, 1.38944548e+03, 3.81100127e-01, 5.08807386e+00],
        [2.72271231e+01, 5.38957364e+02, 9.51217732e-01, 2.05715984e+00],
        [2.42495172e+01, 1.22737989e+03, 3.60030274e-01, 1.01687364e+01],
        [1.34298837e+01, 1.34679776e+03, 9.18289118e-01, 3.93498539e+00],
        [2.69535958e+01, 7.13760315e+02, 1.57642506e-01, 7.33190498e+00],
        [8.13992707e+01, 5.26874518e+02, 3.31769207e-01, 8.18529276e+00],
        [6.84200451e+01, 1.55541557e+03, 5.47249780e-02, 2.52769427e+00],
        [6.93354462e+01, 8.36707533e+02, 8.43525752e-01, 1.06355483e+01],
        [1.61821071e+01, 1.09193709e+03, 4.65673649e-01, 7.95710108e+00],
        [1.65209625e+01, 1.07160370e+03, 4.32342759e-01, 3.04566269e+00],
        [8.27678208e+01, 1.11488843e+03, 8.29461444e-01, 7.48118905e+00],
        [5.00823705e+01, 1.40921905e+0

In [50]:
make_friedman1()

(array([[7.48926843e-01, 5.24848158e-01, 4.62612723e-01, 8.63919141e-01,
         9.69030760e-01, 8.73013850e-01, 4.52644629e-01, 4.93749383e-01,
         1.06011592e-02, 4.33264192e-01],
        [6.39735776e-01, 4.96175493e-01, 7.20700061e-01, 9.88226687e-01,
         8.87443643e-02, 3.10680564e-01, 9.02115730e-01, 1.12989092e-01,
         1.64053790e-01, 6.85767453e-01],
        [7.81911793e-01, 9.30907163e-01, 5.02617702e-01, 8.87764833e-01,
         7.02626637e-01, 4.75986359e-01, 6.83332639e-01, 3.68359905e-01,
         6.90024099e-01, 1.67620772e-01],
        [8.34230534e-01, 9.14219348e-01, 7.90400721e-01, 8.03787536e-01,
         7.57999153e-01, 7.05681538e-02, 2.21078637e-02, 5.11985611e-01,
         1.05027924e-01, 1.65249628e-01],
        [8.35911835e-01, 7.07313477e-01, 4.68523400e-01, 9.57619095e-01,
         7.15077902e-01, 5.57519351e-01, 2.73528149e-02, 3.09776990e-01,
         3.91626992e-01, 6.77797885e-01],
        [1.27610373e-01, 7.65320269e-01, 4.90454154e-01, 1.0

In [49]:
make_classification()

(array([[ 0.80208592, -0.72182849,  0.2248906 , ...,  1.79038096,
         -0.02119605,  0.33422075],
        [ 0.334613  ,  1.5690598 , -0.7785827 , ...,  0.62364558,
          0.26844036,  0.75711169],
        [-1.44873217,  0.96080194, -0.48691348, ...,  0.18344243,
         -0.22469895,  0.50179   ],
        ...,
        [-1.17638299, -1.76224096,  0.97431011, ...,  0.22185116,
          0.36199502,  0.10144695],
        [ 0.39199036, -0.52191076,  0.46766074, ..., -2.06002176,
          1.32133705,  0.52438401],
        [ 1.35921654, -0.28214211,  0.29995085, ..., -1.51307699,
          0.03103509,  1.16783072]]),
 array([1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
        0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
        1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
        1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0]))

In [48]:
make_circles()

(array([[ 5.09939192e-01, -6.16410594e-01],
        [ 8.76306680e-01, -4.81753674e-01],
        [ 9.29776486e-01,  3.68124553e-01],
        [ 7.43821189e-01,  2.94499642e-01],
        [-8.76306680e-01,  4.81753674e-01],
        [ 7.74866529e-01,  1.98951910e-01],
        [-7.28968627e-01,  6.84547106e-01],
        [-9.29776486e-01,  3.68124553e-01],
        [-4.25779292e-01,  9.04827052e-01],
        [ 5.83174902e-01, -5.47637685e-01],
        [-6.27905195e-02,  9.98026728e-01],
        [-1.87381315e-01,  9.82287251e-01],
        [ 8.09016994e-01, -5.87785252e-01],
        [ 9.29776486e-01, -3.68124553e-01],
        [ 7.93691761e-01, -1.00266587e-01],
        [-5.35826795e-01,  8.44327926e-01],
        [ 5.09939192e-01,  6.16410594e-01],
        [-3.40623433e-01,  7.23861642e-01],
        [-9.92114701e-01,  1.25333234e-01],
        [-4.28661436e-01, -6.75462340e-01],
        [ 1.87381315e-01,  9.82287251e-01],
        [-9.29776486e-01, -3.68124553e-01],
        [-1.00000000e+00, -3.216

In [47]:
make_checkerboard()

TypeError: ignored

In [46]:
make_blobs()

(array([[-1.44609156, -2.58278376],
        [-3.13421258, -2.85320869],
        [-5.46869825,  3.67945672],
        [-7.40750848,  1.72238701],
        [-6.79898062,  0.94228355],
        [-1.68306066, -3.48685559],
        [-7.13992833,  2.39890323],
        [-5.61547313,  0.74660556],
        [-8.31118823,  2.16788581],
        [-1.15326844, -3.29007717],
        [-8.52243076,  1.87871892],
        [-6.62250094, -0.03748385],
        [-2.48599125, -3.13655603],
        [-8.29266358,  1.00274998],
        [-1.39653963, -2.53182321],
        [-7.11908072,  4.05851871],
        [-5.47358577,  2.19136982],
        [-2.15249405, -3.74717808],
        [-6.74302034,  4.49114904],
        [-2.26046144, -1.71456086],
        [-7.29217609,  2.63348229],
        [-6.92614724,  1.39317072],
        [-6.2719017 ,  2.03661013],
        [-2.00351399, -1.46394124],
        [-5.69606507,  2.83409107],
        [-2.51065248, -2.3629555 ],
        [-6.36369043,  2.26037289],
        [-7.16800893,  2.136